name: reflector

on:
  workflow_call:
    inputs:
      targetUrl:
        description: 'The event target URL.'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      targetUrl:
        description: 'The event target URL.'
        required: true
        type: string

env:
  GAR_TARGET_URL: ${{ github.event.inputs.targetUrl }}

jobs:
  reflect:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          echo ${{ github.event_name }}
          echo ${{ github.event }}
      - run: npm install request
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./reflector.js')

            let targetUrl = '${{ env.GAR_TARGET_URL }}';

            await script({github, context, targetUrl}).then((result) => {
              console.log(result);
            });
